// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yumhgtfnkamtbbumpoia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1bWhndGZua2FtdGJidW1wb2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NzUyNjYsImV4cCI6MjA4NzQ1MTI2Nn0.6UrP8bIS0b29zv-VzZY46ZpaP-dCurMlUe4C4RPTBow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});